# Generated by Django 5.2.3 on 2025-06-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_main', models.ImageField(upload_to='products/')),
                ('price', models.FloatField()),
                ('test_field', models.CharField(default='test', max_length=10)),
                ('description', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('relax', 'Relax & Refresh'), ('eco', 'Eco-Friendly Care'), ('powders', 'Natural Powders & Scrubs'), ('kits', 'Self-Care Kits')], max_length=20)),
            ],
        ),
    ]
