# Generated by Django 5.2.3 on 2025-06-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases',
            field=models.IntegerField(default=0),
        ),
    ]
