# Generated by Django 5.2.3 on 2025-06-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_purchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_field',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('relax', 'Relax & Refresh'), ('eco', 'Eco-Friendly Care'), ('hair', 'Herbal Hair Care'), ('powders', 'Natural Powders & Scrubs'), ('kits', 'Self-Care Kits')], max_length=20),
        ),
    ]
