# Generated by Django 5.2.3 on 2025-06-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, help_text="List product highlights like 'Biodegradable, Compostable, Reusable'"),
        ),
    ]
